Dev/redirect to login
alveusgg/alveusgg pull request #571
Opened 2024-02-29 17:09 UTC by JonasFranke

## Describe your changes

#567 

## Notes for testing your change

...

2024-03-01 19:52 UTC, JonasFranke commented
Currently, I'm showing an 'unauthorized' text on the sign-in page.
@pjeweb do you want an extra page for that like you said in the issue?

2024-03-04 20:27 UTC, pjeweb requested changes
> Currently, I'm showing an 'unauthorized' text on the sign-in page. @pjeweb do you want an extra page for that like you said in the issue?

Yeah, I think it would be best to 
- redirect unauthenticated users to `/auth/signin` (no message needed) and 
- redirect authenticated users without permissions (unauthorized) to a new page at `/admin/unauthorized`.

2024-03-04 20:27 UTC, pjeweb commented on apps/website/src/pages/auth/signin.tsx
Not sure I get what you are doing here. I think redirecting to the home page after login is still needed. I also do not really think adding another headline is what we want (see review comment).

2024-04-01 18:22 UTC, JonasFranke commented
Sorry for not working on this. I had a lot going on..
I kinda fucked up using git that's why the commits are so weird. Think it's done now

2024-04-02 15:06 UTC, JonasFranke commented
Sorry for the messy commit messages. If you have any idea on how to fix this mess, please let me know!

2024-04-03 14:28 UTC, closed without merging