Added new animals to found animals guide
alveusgg/alveusgg pull request #721
Opened 2024-06-24 17:11 UTC by loganrx8

## Describe your changes

Added four new animals to found animals guide
- Rabbits
- Foxes
- Skunks
- Opossums

2024-06-24 17:34 UTC, pjeweb requested changes
A few small fixes. In general how would you feel about giving sizes in metric too? (cm for inches etc.)

2024-06-24 17:34 UTC, pjeweb commented on apps/website/src/data/found-animal.ts
> +        prompt: ["Does the fox appear to be sick or injured,?"],
```suggestion
        prompt: ["Does the fox appear to be sick or injured?"],
```

2024-06-24 17:34 UTC, pjeweb commented on apps/website/src/data/found-animal.ts
> +                        "If they appear sickly or weak, or if you have reason to believe both parents are dead.",
```suggestion
                        "If they appear sickly or weak, or if you have reason to believe both parents are dead",
```

2024-06-24 17:34 UTC, pjeweb commented on apps/website/src/data/found-animal.ts
> +                      "If you are still concerned you can monitor them from a distance over a period of 24 hours, Keep pets and children away from the area, avoid touching the babies",
```suggestion
                      "If you are still concerned you can monitor them from a distance over a period of 24 hours, keep pets and children away from the area, avoid touching the babies.",
```

2024-06-24 17:34 UTC, pjeweb commented on apps/website/src/data/found-animal.ts
> +              prompt: macros.general.rehab("the rabbit"),
```suggestion
              prompt: macros.general.rehab("the opossum"),
```

2024-06-24 17:37 UTC, loganrx8 commented
> A few small fixes. In general how would you feel about giving sizes in metric too? (cm for inches etc.)

It's fine with me 👍

2024-06-24 18:26 UTC, loganrx8 reviewed
Added sizes in metric.

2024-06-24 21:07 UTC, loganrx8 reviewed
Fixed spelling mistakes

2024-06-28 22:16 UTC, pjeweb approved these changes

2024-06-28 22:21 UTC, pjeweb commented
✅ reviewed by staff

2024-06-29 20:30 UTC, merged