Show & Tell: Add mod comments
alveusgg/alveusgg pull request #736
Opened 2024-08-03 01:15 UTC by ACA30

## Describe your changes

Resolves #716, resolves #717. Adds support for both public & private mod comments on Show & Tell posts.

![image](https://github.com/user-attachments/assets/9ab588ba-565e-4005-bfd7-09dcb4b78079)
![image](https://github.com/user-attachments/assets/4c893251-6391-4a9d-aeae-3cb23313169f)

## Todo
- [x] Add support for mod comments
- [x] Display mod comments in admin area
- [x] Display mod comments in frontend
- [x] Make it pretty

2024-08-03 03:34 UTC, ACA30 commented
![image](https://github.com/user-attachments/assets/46bf0067-7014-497e-91c5-93645443fa07)

2024-08-03 09:28 UTC, pjeweb commented
wow. this looks great! i'll set up a deployment with the database schema changes as soon as i can and then review it in detail

2024-08-10 19:37 UTC, ACA30 commented
@pjeweb saw you reviewing some other PRs - just wanted to check in and see if you had the chance to review this one!

2024-08-10 20:15 UTC, pjeweb requested changes
Looks great already. I only tested locally right now. Let me know if we need it on a public deployment for reviewing!

2024-08-10 20:15 UTC, pjeweb commented on apps/website/src/components/show-and-tell/ShowAndTellEntry.tsx
> +  }
I assume you made this a separate query 'cause fetching them with the posts was messy with types or something? If you can make it work in the main post data a bunch of the following comments will be obsolete.

2024-08-10 20:15 UTC, pjeweb commented on apps/website/src/server/db/show-and-tell.ts
> +      },
This makes it easy to leak the internal mod comments and user data for the mods (including their email). So ideally we should have separate functions for the admin features and I'd probably want this to only explicitly select the username and not the other user fields.

2024-08-10 20:15 UTC, pjeweb commented on apps/website/src/server/db/show-and-tell.ts
> +}
Dito used for both admin and public data, fetches *all* mod comments (including internal ones) and selects all fields from the mod user (incl. email)! Public data should not contain any mod user info, admin data only the username.

2024-08-10 20:15 UTC, pjeweb commented on apps/website/src/server/trpc/router/admin/show-and-tell.ts
> +      return comments;
Is the explicit 404 needed or can this just return the empty result?
```suggestion
      return getModCommentsForEntry(input);
```

2024-08-10 20:15 UTC, pjeweb commented on apps/website/src/server/trpc/router/admin/show-and-tell.ts
> +    }),
Nit pick but we can spare one asyc/await promise resolving by just returning the promise directly here.

```suggestion
    .mutation(({ input }) => addModComment(
      input.entryId,
      input.modId,
      input.comment,
      input.isInternal,
    )),
```

2024-08-10 20:15 UTC, pjeweb commented on apps/website/src/server/trpc/router/show-and-tell.ts
> +      return comments.filter((comment) => !comment.isInternal);
Again make sure we only pass public data here (= no mod user info).

2024-08-10 20:16 UTC, pjeweb commented on apps/website/src/pages/admin/show-and-tell/review/[entryId]/index.tsx
> +                </button>
Can this get a label? We usually give buttons a visual label even tho I like the icon. Also good for accessibility ;)

2024-08-10 20:17 UTC, ACA30 commented
Awesome, tysm! Will make all these updates :)

2024-10-06 16:08 UTC, MattIPv4 commented
No progress, closing.

2024-10-06 16:08 UTC, closed without merging