Show and Tell: Open videos and pictures on click (editor)
alveusgg/alveusgg pull request #746
Opened 2024-08-07 21:55 UTC by ACA30

## Describe your changes

Resolves #565. Allows quick preview of images (in a modal) and videos (open in new tab) on the Show & Tell editor form.

## Notes for testing your change

N/A

2024-08-07 22:10 UTC, ACA30 commented
I missed the ModalDialog component somehow???

2024-08-08 11:26 UTC, bl4nkfce commented
Hey,

For UX and a11y purposes I'd suggest using the `button` element instead of a `div` when triggering the image preview.
It can be a separate "preview" button or you can swap the div for it.

By using the actual `button` element we get all the keyboard support that's expected from an interactive element.
Also, we should set some meaningful `title=` attribute for screen reader users.

2024-08-10 18:41 UTC, pjeweb requested changes
This is great. Thank you for working on this!

2024-08-10 18:41 UTC, pjeweb commented on apps/website/src/components/shared/form/ImageUploadAttachment.tsx
> +        >
Agreeing with @bl4nkfce that this should be a <button>

2024-08-10 18:41 UTC, pjeweb commented on apps/website/src/components/shared/form/VideoLinksField.tsx
oopsie

2024-09-07 18:34 UTC, MattIPv4 commented
👋 @ACA30 any update on this?

2024-10-06 16:08 UTC, MattIPv4 commented
No progress, closing.

2024-10-06 16:08 UTC, closed without merging